sudo: false
language: node_js
node_js:
    - "4"
    - "node"
env:
    - HAPI_VERSION="10"
    - HAPI_VERSION="11"
    - HAPI_VERSION="12"
    - HAPI_VERSION="13"

install:
    - npm install
    - npm install hapi@$HAPI_VERSION
